import { readFileSync, writeFileSync } from 'node:fs';
import { replayScenario } from '../src/replay.mjs';
import { predictIncident, modelInfo } from '../src/ml.mjs';
import { paypalStatus } from '../src/paypal.mjs';
const scenarios = JSON.parse(readFileSync(new URL('../fixtures/scenarios.json', import.meta.url))).scenarios;
const reports = scenarios.map(s => { const r = replayScenario(s); r.ai = predictIncident(r); return r; });
const result = { generatedAt: new Date().toISOString(), scope: 'local synthetic validation; no actual PayPal API calls', sandbox: paypalStatus(), ai: modelInfo(), cases: reports.map(r => ({ id: r.scenario.id, consistency: r.consistency, metrics: r.metrics, ai: { key: r.ai.key, confidence: r.ai.confidence }, evidenceHash: r.evidenceHash })), blockers: ['Successful actual PayPal sandbox probe pending existing credentials.', 'Final public source and demo availability must be checked before submission.', 'Actual <3 minute public YouTube demo pending.'] };
writeFileSync(new URL('../artifacts/validation.json', import.meta.url), JSON.stringify(result, null, 2) + '\n');
writeFileSync(new URL('../artifacts/example-evidence.json', import.meta.url), JSON.stringify(reports[0], null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
